## Libraries

In [1]:
import numpy as np

## Scalar

In [ ]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

## Vector

In [ ]:
x = np.array([42,3,5,3,6,7])
print(x.shape)
x.ndim

(6,)


1

## Matrix

In [ ]:
x = np.array([[42,3,5,3,6,7],
             [66,54,5,343,6,7]])
print(x.shape)
x.ndim

(2, 6)


2

## Tensor

In [ ]:
x = np.array([[[42,3,5,3,6,7],
             [66,54,5,343,6,7]],
             [[42,3,5,3,6,7],
             [66,54,5,343,6,7]],
             [[42,3,5,3,6,7],
             [66,54,5,343,6,7]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

## Reshape

In [3]:
x = np.array([[0,1],
          [2,3],
          [4,5],
          [6,7],
          ])

x.shape

(4, 2)

In [4]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [5]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [8]:
x.T ## Using only ".T" is the same that use .transpose

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])